// BlogPost Mutations
export const LOADING_BLOGS = 'LOADING_ALL_BLOGS';
export const SET_BLOGS = 'SET_BLOGS';
export const SET_A_BLOG = 'SET_A_BLOG',


// Contests Mutations
SET_CONTESTS = 'SET_CONTESTS';
export const SET_A_CONTEST = 'SET_A_CONTEST';
export const LOADING_CONTESTS = 'LOADING_CONTESTS';
export const SET_AN_ENTRY = 'SET_AN_ENTRY';
export const SET_ENTRIES = 'SET_ENTRIES';
export const ENTER_CONTEST = 'ENTER_CONTEST';
export const ENTRY_VOTE = 'ENTRY_VOTE';
export const HOST_A_CONTEST = 'HOST_A_CONTEST';
export const LOADING_ENTRIES = 'LOADING_ENTRIES';

//Events Mutations
export const SET_EVENTS = 'SET_EVENTS';
export const LOADING_EVENTS = 'LOADING_EVENTS';
export const SET_AN_EVENT = 'SET_AN_EVENT',

// UI Mutations types
LOADING_UI = 'LOADING_UI';
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
export const LOADING_DATA = 'LOADING_DATA';
export const SET_CREDENTIALS_ERROR = 'SET_GENERAL_ERROR';
export const SET_EMAIL_ERROR = 'SET_EMAIL_ERROR';
export const SET_PASSWORD_ERROR = 'SET_PASSWORD_ERROR';
export const SET_GENERAL_ERROR = 'SET_GENERAL_ERROR';
// export const SET_LOGIN_ERRORS = 'SET_LOGIN_ERRORS';
// export const SET_SIGNUP_ERRORS = 'SET_SIGNUP_ERRORS';

// User Mutations
export const SET_USERNAMES = 'SET_USERNAMES';
export const GET_TOKEN = 'GET_TOKEN';
export const SET_USER = 'SET_USER';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';

export const SET_ALL_USERS = 'SET_ALL_USERS';
export const LOADING_ALL_USERS = 'LOADING_ALL_USERS';
export const LIKE_AN_ENTRY = 'LIKE_AN_ENTRY';
export const UNLIKE_AN_ENTRY = 'UNLIKE_AN_ENTRY';
export const LIKE_A_BLOGPOST = 'LIKE_A_BLOGPOST';
export const UNLIKE_A_BLOGPOST = 'UNLIKE_A_BLOGPOST';
export const LIKE_AN_EVENT = 'LIKE_AN_EVENT';
export const UNLIKE_AN_EVENT = 'UNLIKE_AN_EVENT';
export const LIKE_A_CONTEST = 'LIKE_A_CONTEST';
export const UNLIKE_A_CONTEST = 'UNLIKE_A_CONTEST';
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';
export const SET_USERS_TIMELINE = 'SET_USERS_TIMELINE';

export const LOADING_USER = 'LOADING_USER';

