export const tags = [
    'video',
    'poetry',
    'water',
    'food',
    'image',
    'visual',
    'photography',
    'art',
    'music',
    'dance',
    'fashion',
    'design & tech',
    'css',
    'water colours',
    'animals',
    'people',
    'colours',
    'nature',
    'apps',
    'bursery',
    'social media',
    'instagram',
    'tiktok',
    'facebook',
    'snapchat',
    'pinterest'
]